config/routes.rb
  Rails.application.routes.draw do

  get 'admin' =>'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new' # Harmful as provided by default and not necessary

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :morders

  resources :lint_items do
    member do
      put 'decrement'
    end
  end

  resources :carts

  get 'store/index'

  resources :products

   root 'store#index', as:'store'

end

app/models/morder.rb
class Morder < ActiveRecord::Base
	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
	has_many :lint_items, dependent: :destroy

	validates :name, :address, :email, presence: true
  	validates :pay_type, inclusion: PAYMENT_TYPES

    def add_lint_items_from_cart(cart)
   		cart.lint_items.each do |item|
      		item.cart_id = nil
      		lint_items << item
     	end
  	end
end

app/controllers/morders_controller.rb
class MordersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_morder, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new,:create]
  # GET /morders
  # GET /morders.json
  def index
    @morders = Morder.all
  end

  # GET /morders/1
  # GET /morders/1.json
  def show
  end

  # GET /morders/new
  def new
    if @cart.lint_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end

    @morder = Morder.new
  end


  # GET /morders/1/edit
  def edit
  end

  # POST /morders
  # POST /morders.json
  def create
    @morder = Morder.new(morder_params)
    @morder.add_lint_items_from_cart(@cart)

    respond_to do |format|
      if @morder.save
        Cart.destroy(session[:cart_id])
        session[:cart_id]=nil
        OrderNotifier.received(@morder).deliver_now #Send mail to user about purchase
        format.html { redirect_to store_url, notice: 'Thank you for Order' }
        format.json { render :show, status: :created, location: @morder }
      else
        format.html { render :new }
        format.json { render json: @morder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /morders/1
  # PATCH/PUT /morders/1.json
  def update
    respond_to do |format|
      if @morder.update(morder_params)
        format.html { redirect_to @morder, notice: 'Morder was successfully updated.' }
        format.json { render :show, status: :ok, location: @morder }
      else
        format.html { render :edit }
        format.json { render json: @morder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /morders/1
  # DELETE /morders/1.json
  def destroy
    @morder.destroy
    respond_to do |format|
      format.html { redirect_to morders_url, notice: 'Morder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morder
      @morder = Morder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def morder_params
      params.require(:morder).permit(:name, :address, :email, :pay_type)
    end
end

app/helpers/morders_helper.rb
module MordersHelper
end

app/views/morders/_form.html.erb
<%= form_for(@morder) do |f| %>
  <% if @morder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@morder.errors.count, "error") %> prohibited this morder from being saved:</h2>

      <ul>
      <% @morder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :pay_type %><br>
    <%= f.select :pay_type, Morder::PAYMENT_TYPES,
                  prompt: 'Select a payment method' %>
  </div>
  <div class="actions">
    <%= f.submit 'Place Order'%>
  </div>
<% end %>

app/views/morders/edit.html.erb
<h1>Editing Morder</h1>

<%= render 'form' %>

<%= link_to 'Show', @morder %> |
<%= link_to 'Back', morders_path %>

app/views/morders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Morders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @morders.each do |morder| %>
      <tr>
        <td><%= morder.name %></td>
        <td><%= morder.address %></td>
        <td><%= morder.email %></td>
        <td><%= morder.pay_type %></td>
        <td><%= link_to 'Show', morder %></td>
        <td><%= link_to 'Edit', edit_morder_path(morder) %></td>
        <td><%= link_to 'Destroy', morder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Morder', new_morder_path %>

app/views/morders/new.html.erb
<div class="depot_form">
  <fieldset>
    <legend>Please Enter Your Details</legend>
    <%= render 'form' %>
  </fieldset>
</div>

app/views/morders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @morder.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @morder.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @morder.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @morder.pay_type %>
</p>

<%= link_to 'Edit', edit_morder_path(@morder) %> |
<%= link_to 'Back', morders_path %>