config/routes.rb
  Rails.application.routes.draw do

  get 'admin' =>'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new' # Harmful as provided by default and not necessary

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :morders

  resources :lint_items do
    member do
      put 'decrement'
    end
  end

  resources :carts

  get 'store/index'

  resources :products

   root 'store#index', as:'store'

end

app/models/lint_item.rb
class LintItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :morder

  def total_price
  	product.price * quantity
  end

  def decrement
  	if self.quantity > 1
  		self.quantity -= 1
  	else
  		self.destroy
  	end
    self
  end
  
end

app/controllers/lint_items_controller.rb
class LintItemsController < ApplicationController
  include CurrentCart
  before_action :set_lint_item, only: [:show, :edit, :update, :destroy, :decrement]
  before_action :set_cart, only: [:create, :decrement]
  skip_before_action :authorize, only: [:create, :decrement]
  # GET /lint_items
  # GET /lint_items.json
  def index
    @lint_items = LintItem.all
  end


  def decrement # To decrement , created a route 
    @lint_item = @lint_item.decrement  
    respond_to do |format|
      if @lint_item.save
        format.html { redirect_to store_url}
        format.js {@current_item = @lint_item}
      end
    end
  end

  # GET /lint_items/1
  # GET /lint_items/1.json
  def show
  end

  # GET /lint_items/new
  def new
    @lint_item = LintItem.new
  end

  # GET /lint_items/1/edit
  def edit
  end

  # POST /lint_items
  # POST /lint_items.json
  def create
    product = Product.find(params[:product_id])
    @lint_item = @cart.add_product(product.id)
    #session[:counter]=0


    respond_to do |format|
      if @lint_item.save
        format.js   { @current_item = @lint_item }
        format.html { redirect_to store_url}#notice was removed as we did not need it 
        format.json { render :show, status: :created, location: @lint_item }
      else
        format.html { render :new }
        format.json { render json: @lint_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lint_items/1
  # PATCH/PUT /lint_items/1.json
  def update
    respond_to do |format|
      if @lint_item.update(lint_item_params)
        format.html { redirect_to @lint_item, notice: 'Lint item was successfully updated.' }
        format.json { render :show, status: :ok, location: @lint_item }
      else
        format.html { render :edit }
        format.json { render json: @lint_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lint_items/1
  # DELETE /lint_items/1.json
  def destroy
    @lint_item.destroy
    respond_to do |format|
      format.html { redirect_to lint_items_url }
      format.json { head :no_content }
    end
=begin
    @lint_item = LintItem.find(params[:id])
    @lint_item.destroy
    respond_to do |format|
      if @lint_item.cart.lint_items.empty?
        format.html { redirect_to store_url, notice: 'Your cart is empty' }
      else  
        format.html { redirect_to @lint_item.cart, notice: 'Product was successfully Removed.'}
      end
        format.json { head :no_content }
      end
=end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lint_item
      @lint_item = LintItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lint_item_params
      params.require(:lint_item).permit(:product_id)
    end
end

app/helpers/lint_items_helper.rb
module LintItemsHelper
end

app/views/lint_items/_form.html.erb
<%= form_for(@lint_item) do |f| %>
  <% if @lint_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lint_item.errors.count, "error") %> prohibited this lint_item from being saved:</h2>

      <ul>
      <% @lint_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lint_items/_lint_item.html.erb
<% if lint_item == @current_item %> <!--Finding the element to be highlighted  -->
<tr id = "current_item">
<% else %>
<tr>
<% end %>
      <td><%= lint_item.quantity %>&times;</td>
      <td><%= lint_item.product.title %></td>
      <td class="item_price"><%= number_to_currency(lint_item.total_price) %></td>
      <td>
      	<%= button_to 'X', decrement_lint_item_url(lint_item),method: :put,remote: true,class: "buttonRemove" %>
      </td>

      

      <!--We have also changed to lint_item which works thankx to rails magic -->
</tr>

app/views/lint_items/_lint_item.text.erb
<%= sprintf("%2d x %s",
            lint_item.quantity,
            truncate(lint_item.product.title, length: 50)) %>

app/views/lint_items/create.js.erb
$('#notice').hide(); //For hiding the order notice

if( $('#cart tr').length == 1){ $('#cart').show('blind',1000);}

$('#cart').html("<%= escape_javascript render(@cart)%>");

$('#current_item').css({'background-color':'#FA5858'}).
  animate({'background-color':'#CEF6EC'}, 1000);

app/views/lint_items/decrement.js.erb
$('#cart').html("<%=escape_javascript render @cart %>");

$('#current_item').css({'background-color':'#FA5858'}).
  animate({'background-color':'#CEF6EC'}, 1000);

  if ($('#cart tr').length==1) {
    // Hide the cart
    $('#cart').hide('blind', 1000);    
}

app/views/lint_items/edit.html.erb
<h1>Editing Lint Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @lint_item %> |
<%= link_to 'Back', lint_items_path %>

app/views/lint_items/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Lint Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lint_items.each do |lint_item| %>
      <tr>
        <td><%= lint_item.product %></td>
        <td><%= lint_item.cart %></td>
        <td><%= link_to 'Show', lint_item %></td>
        <td><%= link_to 'Edit', edit_lint_item_path(lint_item) %></td>
        <td><%= link_to 'Destroy', lint_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lint item', new_lint_item_path %>

app/views/lint_items/new.html.erb
<h1>New Lint Item</h1>

<%= render 'form' %>

<%= link_to 'Back', lint_items_path %>

app/views/lint_items/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Product:</strong>
  <%= @lint_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @lint_item.cart %>
</p>

<%= link_to 'Edit', edit_lint_item_path(@lint_item) %> |
<%= link_to 'Back', lint_items_path %>