config/routes.rb
  Rails.application.routes.draw do

  get 'admin' =>'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new' # Harmful as provided by default and not necessary

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :morders

  resources :lint_items do
    member do
      put 'decrement'
    end
  end

  resources :carts

  get 'store/index'

  resources :products

   root 'store#index', as:'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
<div id="banner">
	<%= image_tag("logo.png")%>
	<%= page_title %>

		<%# ActionMailer::Base.deliveries.count %>

</div>
<div id="columns">
	<div id="side">
		<% if @cart%>
		<%= hidden_div_if(@cart.lint_items.empty?, id: 'cart') do %>
        	<%= render @cart %>
      	<% end %>
      	<% end %>
		<ul>
			<li> <a href="http://www....">Home</a></li>
			<li> <a href="http://www..../faq">FAQ</a></li>
			<li> <a href="http://www..../news">News</a></li>
			<li> <a href="http://www..../contact">Contact</a></li>
			<li> <%= @time %></li>
			<li> <%= @date %></li>
		</ul>	

		<% if session[:user_id] %>
			<ul>
				<li><%=link_to 'Orders',morders_path %></li>
				<li><%=link_to 'Products',products_path %></li>
				<li><%=link_to 'Users',users_path %></li>
			</ul>
			<%= button_to 'Logout', logout_path,method: :delete%>
		<%else %>
			<%= button_to 'Login', login_path,method: :get%>	
		<%end%>
	</div>
	<div id="main">
		<%= yield %>
	</div>
</div>



</body>
</html>